[build]
  command = "npm run build"  # Commande pour construire le client
  publish = "client/build"   # Dossier de construction du client

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
