[build]
  command = "npm run build"  # Commande pour construire le client
  publish = "client/build"  # Dossier de construction du client

[[redirects]]
  from = "/*"
  to = "/index.js"  # Redirection vers le fichier index.html du client
  status = 200
